"""LIR — target-shaped IR.

Each backend defines its own LIR dialect. Rust LIR has explicit lifetimes and
Result-based error handling; C LIR is flat; Mojo LIR distinguishes var/let/fn.
Keeping these separate prevents the MIR from absorbing target-specific concerns.

For the initial Python -> Rust slice, only the Rust dialect is populated.
"""

from .base import LirNode
from .rust import *
from .c import *
from .mojo import *
from .py import *
from .fortran import *

__all__ = [
    "LirNode",
    "RustModule",
    "RustFn",
    "RustReturn",
    "RustBinOp",
    "RustName",
    "RustIntLiteral",
    "RustFloatLiteral",
    "RustBoolLiteral",
    "RustStringLiteral",
    "RustCompare",
    "RustBoolOp",
    "RustUnary",
    "RustIf",
    "RustWhile",
    "RustForRange",
    "RustLet",
    "RustReassign",
    "RustVec",
    "RustIndex",
    "RustMethodCall",
    "RustCall",
    "RustStruct",
    "RustImpl",
    "RustFieldAccess",
    "RustFieldAssign",
    "RustStructInit",
    "RustSubscriptAssign",
    "RustFormat",
    "RustMacro",
    "RustMethodChain",
    "RustBreak",
    "RustContinue",
    "RustRaw",
    "CFieldAssign",
    "CStructInit",
    "CSubscriptAssign",
    "CModule",
    "CFn",
    "CReturn",
    "CBinOp",
    "CCompare",
    "CBoolOp",
    "CUnary",
    "CName",
    "CIntLiteral",
    "CFloatLiteral",
    "CBoolLiteral",
    "CStringLiteral",
    "CIf",
    "CWhile",
    "CForRange",
    "CDecl",
    "CReassign",
    "CIndex",
    "CCall",
    "CTernary",
    "CStruct",
    "CFieldAccess",
    "CBreak",
    "CContinue",
    "CRaw",
    "MojoFieldAssign",
    "MojoStructInit",
    "MojoSubscriptAssign",
    "MojoStruct",
    "MojoFieldAccess",
    "MojoModule",
    "MojoFn",
    "MojoReturn",
    "MojoBinOp",
    "MojoCompare",
    "MojoBoolOp",
    "MojoUnary",
    "MojoName",
    "MojoIntLiteral",
    "MojoFloatLiteral",
    "MojoBoolLiteral",
    "MojoStringLiteral",
    "MojoIf",
    "MojoWhile",
    "MojoForRange",
    "MojoVar",
    "MojoReassign",
    "MojoList",
    "MojoIndex",
    "MojoCall",
    "MojoMethodCall",
    "MojoBreak",
    "MojoContinue",
    "MojoRaw",
    "PyFieldAssign",
    "PyStructInit",
    "PySubscriptAssign",
    "PyModule",
    "PyFn",
    "PyReturn",
    "PyBinOp",
    "PyCompare",
    "PyBoolOp",
    "PyUnary",
    "PyName",
    "PyIntLiteral",
    "PyFloatLiteral",
    "PyBoolLiteral",
    "PyStringLiteral",
    "PyIf",
    "PyWhile",
    "PyForRange",
    "PyAssign",
    "PyCall",
    "PyClass",
    "PyFieldAccess",
    "PyBreak",
    "PyContinue",
    "PyRaw",
    "FortranFieldAssign",
    "FortranStructInit",
    "FortranSubscriptAssign",
    "FortranModule",
    "FortranFn",
    "FortranAssign",
    "FortranReturn",
    "FortranBinOp",
    "FortranCompare",
    "FortranBoolOp",
    "FortranUnary",
    "FortranName",
    "FortranIntLiteral",
    "FortranFloatLiteral",
    "FortranBoolLiteral",
    "FortranStringLiteral",
    "FortranIf",
    "FortranWhile",
    "FortranForRange",
    "FortranCall",
    "FortranType",
    "FortranFieldAccess",
    "FortranArrayLit",
    "FortranSubscript",
    "FortranExit",
    "FortranCycle",
    "FortranRaw",
]
